### ISSUE TITLE
Training MSNet3D error

### ISSUE THREAD

**Issue by YznMur** [cogsys-tuebingen/mobilestereonet#14]
I am trying to train MSNet3D on stereodriving and KITTI2015 but faced this error:

 File "train.py", line 205, in <module>
    train()
  File "train.py", line 98, in train
    loss, scalar_outputs, image_outputs = train_sample(sample, compute_metrics=do_summary)
  File "train.py", line 155, in train_sample
    disp_ests = model(imgL, imgR)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 171, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/trainer/mobile_stereo/models/MSNet3D.py", line 124, in forward
    out1 = self.encoder_decoder1(cost0)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/trainer/mobile_stereo/models/MSNet3D.py", line 46, in forward
    conv5 = F.relu(self.conv5(conv4) + self.redir2(conv2), inplace=True)
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 2

Does anybody know how to solve this problem?
Looking forward to your reply！

**Comment by samuel-woerz** [comment]
What arguments are you giving the train.py function?

**Comment by YznMur** [comment]
Thanks for your reply
I am giving these arguments:
python train.py --dataset drivingstereo --datapath /home/trainer/Datasets/drivingstereo/ --trainlist ./filenames/ds_train.txt --testlist ./filenames/ds_test.txt --epochs 400 --lrepochs "200:10" --batch_size 1 --test_batch_size 1 --model MSNet3D  --logdir ./log_drivingstereo/

**Comment by samuel-woerz** [comment]
I freshly pulled the code and used the same arguments as you did (only changing the data path), but I can't replicate your error.

**Comment by samuel-woerz** [comment]
When does it throw the error?

**Comment by flyxuexi** [comment]
> When does it throw the error?

3D-mobilestereonet can not reach the test results of kitti2015，why？thanks。I used the MSNet3D_SF_KITTI2015.ckpt you provided.We submitted the parallax map to the kitti website, but the results were very different from those in the paper. In the paper, it is 1.75 3.87 2.10 1.61 3.50 1.92, but what I measured is 2.01 4.40 2.40 1.85 3.88 2.18, is it the wrong way for me to fine-tune, or is it for some other reason? Please help me.
